const express = require("express");
const app = express();

const top10Movies = [
  {
    name: "The Dark Knight",
    "release date": "July 18, 2008",
    genres: ["action", "drama", "crime", "thriller", "superhero"],
    "top billed castors": [
      "Christian Bale",
      "Heath Ledger",
      "Aaron Eckhart",
      "Michael Caine",
      "Maggie Gyllenhall",
      "Gary Oldman",
      "Morgan Freeman",
      "Monique Gabriela Curnen",
      "Ron Dean",
    ],
    director: "Christopher Nolan",
  },
  {
    name: "The Lord of the Rings: The Fellowship of the Ring",
    "release date": "December 19, 2001",
    genres: ["action", "adventure", "fantasy"],
    "top billed castors": [
      "Elijah Wood",
      "Ian McKellen",
      "Viggo Mortensen",
      "Sean Astin",
      "Ian Holm",
      "Liv Tyler",
      "Christopher Lee",
      "Sean Bean",
      "Billy Boyd",
    ],
    director: "Peter Jackson",
  },
  {
    name: "Inception",
    "release date": "July 16, 2010",
    genres: ["action", "adventure", "science fiction"],
    "top billed castors": [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Ken Watanabe",
      "Tom Hardy",
      "Elliot Page",
      "Dileep Rao",
      "Tom Berenger",
      "Marion Cotillard",
    ],
    director: "Christopher Nolan",
  },
  {
    name: "Warrior",
    "release date": "September 9, 2011",
    genres: ["action", "drama"],
    "top billed castors": [
      "Joel Edgerton",
      "Tom Hardy",
      "Nick Nolte",
      "Jennifer Morrison",
      "Frank Grillo",
      "Kevin Dunn",
      "Maximiliano Hernández",
      "Bryan Callen",
      "Sam Sheridan",
    ],
    director: "Gavin O'Connor",
  },
  {
    name: "Never Back Down",
    "release date": "March 4, 2008",
    genres: ["action", "drama"],
    "top billed castors": [
      "Sean Faris",
      "Amber Heard",
      "Cam Gigandet",
      "Djimon Hounsou",
      "Evan Peters",
      "Leslie Hope",
      "Wyatt Smith",
      "Neil Brown Jr.",
      "Lauren Leech",
    ],
    director: "Jeff Wadlow",
  },
  {
    name: "Rocky",
    "release date": "November 20, 1976",
    genres: ["drama"],
    "top billed castors": [
      "Sylvester Stallone",
      "Talia Shire",
      "Burt Young",
      "Carl Weathers",
      "Burgess Meredith",
      "Thayer David",
      "Joe Spinell",
      "Jimmy Gambina",
      "Bill Baldwin",
    ],
    director: "John G. Avildsen",
  },
  {
    name: "Ong-Bak",
    "release date": "October 17, 2004",
    genres: ["action", "thriller", "crime", "adventure"],
    "top billed castors": [
      "Tony Jaa",
      "Petchtai Wongkamlao",
      "Patrarin Punyanutatam",
      "Suchao Pongwilai",
      "Choomporn Theppitak",
      "Cheathavuth Watcharakhun",
      "Wannakit Sirioput",
      "Rungrawee Barijindakul",
      "Chatthapong Phantana-Angkul",
    ],
    director: "Prachya Pinkaew",
  },
];
